- name: Apply all roles
  hosts: localhost

  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      become: yes

    - name: Set zsh as default shell
      user:
        name: "{{ current_user }}"
        shell: /bin/zsh
      become: yes

  tasks:
    - include_role:
        name: base
    - include_role:
        name: dotfiles
