- name: Apply all roles
  hosts: localhost
  become: yes

  pre_tasks:
    - name: Update package cache
      apt:
        update_cache: yes

  - include_role: base
  - include_role: dotfiles

  post_tasks:
    - name: Schedule system restart
      command: shutdown -r +1 "Ansible provisioning complete. Rebooting in 1 minute."
      async: 0
      poll: 0
      ignore_errors: true

    - name: Wait for 10 seconds before ending play
      pause:
        seconds: 10

    - name: End play
      meta: end_play
