- name: Install ags dependencies
  kewlfft.aur.aur:
    use: paru
    name:
      - dart-sass
      - swww
      - matugen
      - slurp
      - wf-recorder
      - wayshot-bin
      - swappy
      - supergfxctl
      - gnome-bluetooth-3.0
    state: present
  become: yes
  become_user: "{{ current_user }}"

- name: Enable and start the supergfxctl service
  systemd:
    name: supergfxd
    enabled: yes
    state: started
  become: yes

- name: Install bun
  shell: curl -fsSL https://bun.sh/install | bash
  become: yes
  become_user: "{{ current_user }}"

- name: Symlink to /usr/bin
  shell: ln -sf /home/{{ current_user }}/.bun/bin/bun /usr/bin/bun

- name: Install ags
  kewlfft.aur.aur:
    use: paru
    name:
      - aylurs-gtk-shell
    state: present
  become: yes
  become_user: "{{ current_user }}"
