# Download a zip from url and extract it to a directory
- name: Download and extract sddm catppuccin theme
  unarchive:
    src: https://github.com/catppuccin/sddm/releases/download/v1.0.0/catppuccin-mocha.zip
    dest: /usr/share/sddm/themes/
    remote_src: yes
    creates: /usr/share/sddm/themes/catppuccin-mocha

- name: Ensure SDDM configuration directory exists
  file:
    path: /etc/sddm.conf.d/
    state: directory
    mode: "0755"

- name: Configure SDDM theme
  ini_file:
    path: /etc/sddm.conf.d/theme.conf
    section: Theme
    option: Current
    value: catppuccin-mocha
    mode: "0644"
    create: yes

- name: Install catppuccin theme for grub
  kewlfft.aur.aur:
    use: paru
    name:
      - catppuccin-mocha-grub-theme-git
    state: present
  become: yes
  become_user: "{{ current_user }}"

- name: Set catppuccin theme for grub
  lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_THEME="
    line: 'GRUB_THEME="/usr/share/grub/themes/catppuccin-mocha/theme.txt"'

- name: Regenerate GRUB configuration
  shell: sudo grub-mkconfig -o /boot/grub/grub.cfg

- name: Clean up temporary files
  file:
    path: "/tmp/catppuccin-grub"
    state: absent

- name: Install catppuccin theme for gtk
  kewlfft.aur.aur:
    use: paru
    name:
      - catppuccin-gtk-theme-mocha
    state: present
  become: yes
  become_user: "{{ current_user }}"

- name: Install powerlevel10k
  kewlfft.aur.aur:
    use: paru
    name: zsh-theme-powerlevel10k-git
    state: present
  become: yes
  become_user: "{{ current_user }}"

- name: Install kora icon theme
  kewlfft.aur.aur:
    use: paru
    name: kora-icon-theme
    state: present
  become: yes
  become_user: "{{ current_user }}"

- name: Install catppuccin cursors
  kewlfft.aur.aur:
    use: paru
    name: catppuccin-cursors-mocha
    state: present
  become: yes
  become_user: "{{ current_user }}"
