- name: Clone the dotfiles repository
  git:
    repo: https://github.com/Coelhomatias/.dotfiles.git
    dest: /home/{{ current_user }}/.dotfiles
    single_branch: yes
    version: aylur

- name: Stow the dotfiles
  shell: cd /home/{{ current_user }}/.dotfiles && stow --adopt -S bat btop conda fonts git nvim yazi zsh-ubuntu --no-folding

- name: Restore git repo
  shell: cd /home/{{ current_user }}/.dotfiles && git restore .
  become: yes
  become_user: "{{ current_user }}"

- include_tasks: themes.yml
