- name: Clone the dotfiles repository
  git:
    repo: https://github.com/Coelhomatias/.dotfiles.git
    dest: /home/{{ ansible_env.USER }}/.dotfiles
    single_branch: yes
    version: hyprland
  become: yes
  become_user: "{{ ansible_env.USER }}"

- name: Stow the dotfiles
  shell: cd /home/{{ ansible_env.USER }}/.dotfiles && stow --adopt .
  become: yes
  become_user: "{{ ansible_env.USER }}"

- name: Restore git repo
  shell: cd /home/{{ ansible_env.USER }}/.dotfiles && git restore .
  become: yes
  become_user: "{{ ansible_env.USER }}"

- include_tasks: themes.yml
