- name: Apply GTK themes
  shell: nwg-look -a
  become: yes
  become_user: "{{ current_user }}"

- name: Rebuild bat's cache
  shell: bat cache --build
  become: yes
  become_user: "{{ current_user }}"

- name: Install kora icon theme
  kewlfft.aur.aur:
    use: paru
    name: kora-icon-theme
    state: present
  become: yes
  become_user: "{{ current_user }}"
