---
- name: Install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-pulse
      - pipewire-audio
      - wireplumber
      - pamixer
      - pavucontrol
    state: present

- name: Enable pipewire service
  shell: systemctl --user enable --now pipewire
  become: yes
  become_user: "{{ ansible_env.USER }}"

- name: Enable pipewire-pulse service
  shell: systemctl --user enable --now pipewire-pulse
  become: yes
  become_user: "{{ ansible_env.USER }}"
