- name: Install battery management packages
  pacman:
    name:
      - tlp
      - tlp-rdw
      - upower
    state: present

- name: Enable tlp service
  systemd:
    name: tlp
    enabled: yes
    state: started

- name: Mask sytemd-rfkill service
  systemd:
    name: systemd-rfkill
    masked: yes
    state: stopped

- name: Mask systemd-rfkill.socket service
  systemd:
    name: systemd-rfkill.socket
    masked: yes
    state: stopped
