- name: Create a directory for Miniconda
  file:
    path: "~/miniconda3"
    state: directory

- name: Download Miniconda installation script
  get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: "~/miniconda3/miniconda.sh"

- name: Install Miniconda
  shell: bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
  args:
    creates: "~/miniconda3/bin/conda"

- name: Remove Miniconda installation script
  file:
    path: "~/miniconda3/miniconda.sh"
    state: absent

- name: Init conda for zsh
  shell: ~/miniconda3/bin/conda init zsh
