---
- include_tasks: aur_helper.yml
- include_tasks: system_packages.yml

- name: Check for GPU type using lspci
  shell: "lspci | grep -iE 'vga|display'"
  register: gpu_info

- name: Include tasks from amd.yml if AMD GPU is detected
  include_tasks: amd.yml
  when: "'AMD' in gpu_info.stdout"

- name: Include tasks from nvidia.yml if NVIDIA GPU is detected
  include_tasks: nvidia.yml
  when: "'NVIDIA' in gpu_info.stdout"

- include_tasks: battery.yml
- include_tasks: audio.yml
- include_tasks: bluetooth.yml
- include_tasks: utils.yml
- include_tasks: fonts.yml
- include_tasks: terminal.yml
