- name: Add zsh-completions repository
  ansible.builtin.apt_repository:
    repo: deb http://download.opensuse.org/repositories/shells:/zsh-users:/zsh-completions/xUbuntu_22.04/ /
    state: present
    filename: shells_zsh-users_zsh-completions

- name: Add GPG key for zsh-completions repository
  ansible.builtin.get_url:
    url: https://download.opensuse.org/repositories/shells:zsh-users:zsh-completions/xUbuntu_22.04/Release.key
    dest: /tmp/zsh-completions-repo.key
    mode: "0644"

- name: Import GPG key
  ansible.builtin.command: gpg --dearmor /tmp/zsh-completions-repo.key
  register: gpg_result
  changed_when: gpg_result.rc == 0

- name: Move GPG key to trusted.gpg.d
  ansible.builtin.copy:
    content: "{{ gpg_result.stdout }}"
    dest: /etc/apt/trusted.gpg.d/shells_zsh-users_zsh-completions.gpg
    mode: "0644"

- name: Remove temporary GPG key file
  ansible.builtin.file:
    path: /tmp/zsh-completions-repo.key
    state: absent

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install zsh and plugins
  ansible.builtin.apt:
    name:
      - zsh
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-autosuggestions
    state: present

- name: Set zsh as default shell
  command: chsh -s /usr/bin/zsh "{{ current_user }}"

- name: Install brew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  args:
    creates: /home/{{ current_user }}/homebrew

- name: Install zsh-you-should-use with brew
  homebrew:
    name: zsh-you-should-use
    state: present
