- name: Install brew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- name: Install zsh and plugins with brew
  homebrew:
    name:
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - zsh-you-should-use
    state: present
