- name: Install brew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- name: Check if ~/.linuxbrew exists
  ansible.builtin.stat:
    path: ~/.linuxbrew
  register: user_linuxbrew

- name: Set Homebrew environment variables for user installation
  ansible.builtin.shell: eval "$(~/.linuxbrew/bin/brew shellenv)"
  when: user_linuxbrew.stat.exists
  changed_when: false

- name: Check if /home/linuxbrew/.linuxbrew exists
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew
  register: system_linuxbrew

- name: Set Homebrew environment variables for system installation
  ansible.builtin.shell: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
  when: system_linuxbrew.stat.exists
  changed_when: false

- name: Get Homebrew prefix
  ansible.builtin.command: brew --prefix
  register: brew_prefix
  changed_when: false

- name: Add Homebrew to .zshrc
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: 'eval "$({{ brew_prefix.stdout }}/bin/brew shellenv)"'
    state: present

- name: Install zsh and plugins with brew
  homebrew:
    name:
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - zsh-you-should-use
    state: present
