- name: Install brew
  ansible.builtin.shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

- name: Check if ~/.linuxbrew exists
  ansible.builtin.stat:
    path: ~/.linuxbrew
  register: user_linuxbrew

- name: Set Homebrew environment variables for user installation
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: eval "$(~/.linuxbrew/bin/brew shellenv)"
    state: present
  when: user_linuxbrew.stat.exists

- name: Check if /home/linuxbrew/.linuxbrew exists
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew
  register: system_linuxbrew

- name: Set Homebrew environment variables for system installation
  ansible.builtin.lineinfile:
    path: ~/.zshrc
    line: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
    state: present
  when: system_linuxbrew.stat.exists

- name: Install zsh and plugins with brew
  homebrew:
    name:
      - zsh-completions
      - zsh-syntax-highlighting
      - zsh-autosuggestions
      - zsh-you-should-use
    state: present

- name: Install dev packages
  apt:
    name:
      - fontconfig
      - make
      - gcc
      - g++
    state: present
  become: yes
